find_package(Threads REQUIRED)
add_library(rp_scenario_execution STATIC running_scenario.cpp ../simulator/telemetry.cpp)
target_include_directories(rp_scenario_execution PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}
  PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../simulator)
target_link_libraries(rp_scenario_execution PUBLIC rp_config rp_simulation_view Threads::Threads)
rp_project_options(rp_scenario_execution)
add_executable(robotics-sim-view main.cpp)
target_link_libraries(robotics-sim-view PRIVATE rp_viewer_desktop rp_scenario_execution)
rp_project_options(robotics-sim-view)
set_target_properties(robotics-sim-view PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR})
install(TARGETS robotics-sim-view RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
if(BUILD_TESTING)
  find_package(GTest REQUIRED CONFIG)
  add_executable(scenario_execution_tests running_scenario_test.cpp)
  target_compile_definitions(scenario_execution_tests PRIVATE RP_CONTENT="${PROJECT_SOURCE_DIR}/content")
  target_link_libraries(scenario_execution_tests PRIVATE rp_scenario_execution GTest::gtest_main)
  rp_project_options(scenario_execution_tests)
  include(GoogleTest)
  gtest_discover_tests(scenario_execution_tests DISCOVERY_MODE PRE_TEST)
endif()
