find_package(glfw3 3.3 REQUIRED)
find_package(OpenGL REQUIRED)
find_package(GLEW REQUIRED)
add_executable(robotics-render-capture main.cpp)
target_link_libraries(robotics-render-capture PRIVATE rp_scene_rendering glfw OpenGL::GL GLEW::GLEW)
target_include_directories(robotics-render-capture SYSTEM PRIVATE ${PROJECT_SOURCE_DIR}/third_party/glm)
rp_project_options(robotics-render-capture)
set_target_properties(robotics-render-capture PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR})
install(TARGETS robotics-render-capture RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
