"""riptide_mpc model files for the plant a nereus run actually simulates.

The MPC's default model (riptide_mpc config/models/talos.yaml) is the pool-identified estimate of the real
vehicle, and mpc.yaml carries the real Nortek DVL latency. Under nereus both are wrong: the sim plant has its own
mass/volume/COB/drag and a 0.1 s lagged-force thruster model. This writes, from the resolved scenario:

    vehicle.yaml          riptide_descriptions <robot>.yaml with mass, COM, base_link and thruster poses
                          replaced by the plant's
    hydrodynamics.yaml    riptide_mpc hydrodynamics schema 1 from the plant body, pool and thrusters
    mpc.yaml              riptide_mpc mpc.yaml with estimator.dvl_latency = 0: the simulator stamps every reading
                          when it is taken (latency_s only delays delivery), like the fixed Nortek driver

Both sides use the same MarineDynamics (inertia about the COM in body axes, COB/damping centre relative to
the COM), so the body parameters copy over unchanged.

    python3 mpc_sim_model.py <run>.resolved.json <out_dir> <descriptions robot.yaml> <mpc.yaml>
"""

import json
import math
import sys
from pathlib import Path

import yaml


def _transforms(robot):
    return {t["child"]: t for t in robot["frames"]["transforms"]}


def _in_origin(transforms, child):
    """Position of `child` in the vehicle origin frame (the riptide_descriptions frame)."""
    t = transforms[child]
    if t["parent"] == "origin":
        return list(t["position_m"])
    raise ValueError(f"{child}: expected a transform from origin, got parent {t['parent']}")


def _com_in_origin(transforms):
    t = transforms["origin"]
    if t["parent"] != "com" or t["orientation_wxyz"] != [1.0, 0.0, 0.0, 0.0]:
        raise ValueError("expected an unrotated com -> origin transform")
    return [-v for v in t["position_m"]]


def _axis(q):
    """Body x axis of a wxyz quaternion: the thruster's force direction."""
    w, x, y, z = q
    return [1 - 2 * (y * y + z * z), 2 * (x * y + w * z), 2 * (x * z - w * y)]


def _same(params, key, name):
    values = {json.dumps(p["parameters"][key]) for p in params}
    if len(values) != 1:
        raise ValueError(f"thrusters differ in {key}; the MPC model has one {name} for all thrusters")
    return params[0]["parameters"][key]


def vehicle(resolved, descriptions):
    robot = resolved["robot"]
    tf = _transforms(robot)
    out = dict(descriptions)
    out["mass"] = robot["body"]["parameters"]["mass_kg"]
    out["com"] = _com_in_origin(tf)
    if "base_link" in tf:
        out["base_link"] = _in_origin(tf, "base_link")
    order = resolved["bridge"]["thrusters"]["order"]
    names = [t["name"] for t in descriptions["thrusters"]]
    if names != order:
        raise ValueError(f"thruster order differs: descriptions {names}, sim bridge {order}")
    thrusters = []
    for entry in descriptions["thrusters"]:
        frame = tf[f"thruster_{entry['name']}"]
        dx, dy, dz = _axis(frame["orientation_wxyz"])
        # The MPC only uses rpy -> direction (rotated x), so roll is free.
        pose = _in_origin(tf, f"thruster_{entry['name']}") + [0.0, -math.asin(max(-1.0, min(1.0, dz))),
                                                               math.atan2(dy, dx)]
        thrusters.append({**entry, "pose": pose})
    out["thrusters"] = thrusters
    return out


def hydrodynamics(resolved):
    robot, pool = resolved["robot"], resolved["pool"]["parameters"]
    body = robot["body"]["parameters"]
    thrusters = robot["thrusters"]
    kinds = {t["type"] for t in thrusters}
    if kinds != {"lagged_force"}:
        raise ValueError(f"thruster type {sorted(kinds)}: only lagged_force maps onto the MPC thruster model")
    order = resolved["bridge"]["thrusters"]["order"]
    by_id = {t["id"]: t for t in thrusters}
    scales = resolved["bridge"]["thrusters"].get("input_scales", [1] * len(order))
    p = thrusters[0]["parameters"]
    for key in ("delay_s", "rise_time_s", "fall_time_s", "slew_rate_n_s", "forward_limit_n", "reverse_limit_n",
                "deadband_n", "propeller_radius_m"):
        _same(thrusters, key, key)
    # Forward/reverse scales may differ per thruster (identified per thruster); riptide_mpc reads them as
    # thruster_forward_scales / thruster_reverse_scales (bridge order), else the shared values.
    per_thruster = {}
    for key, name in (("forward_scale", "thruster_forward_scales"), ("reverse_scale", "thruster_reverse_scales")):
        values = [by_id[thruster]["parameters"][key] for thruster in order]
        if len(set(values)) > 1:
            per_thruster[name] = values
    return {
        "schema_version": 1,
        "robot": robot["id"],
        "parameter_status": "sim_plant",
        "provenance": "Generated by nereus integrations/uwrt/launch/mpc_sim_model.py from the resolved scenario",
        "rigid_body_inertia3x3": [v for row in body["inertia_matrix"] for v in row],
        "added_mass6x6": body["added_mass_matrix"],
        "linear_damping6x6": body["linear_damping_matrix"],
        "quadratic_damping": body["quadratic_damping"],
        "damping_center_relative": body.get("damping_center_m", [0.0, 0.0, 0.0]),
        "water_density": pool["water_density_kg_m3"],
        "displaced_volume": body["displaced_volume_m3"],
        "cob_relative": body["buoyancy_center_m"],
        "buoyancy_radii": body["buoyancy_radii_m"],
        "water_level": pool.get("water_level_m", 0.0),
        "current_velocity": pool.get("current_m_s", [0.0, 0.0, 0.0]),
        "current_oscillation_amplitude": pool.get("current_oscillation_amplitude_m_s", [0.0, 0.0, 0.0]),
        "current_oscillation_frequency": pool.get("current_oscillation_frequency_hz", 0.0),
        "thruster_dynamics": {
            "delay": p["delay_s"],
            "rise_time_constant": p["rise_time_s"],
            "fall_time_constant": p["fall_time_s"],
            "slew_rate": p["slew_rate_n_s"],
            "force_deadband": p["deadband_n"],
            "forward_scale": p["forward_scale"],
            "reverse_scale": p["reverse_scale"],
            "command_timeout": body.get("command_timeout_s", 0.5),
            "forward_max_force": p["forward_limit_n"],
            "reverse_max_force": p["reverse_limit_n"],
            "propeller_radius": p["propeller_radius_m"],
        },
        "thruster_efficiencies": [by_id[name]["parameters"]["efficiency"] * scale
                                  for name, scale in zip(order, scales)],
        **per_thruster,
    }


def mpc_params(resolved, base):
    """estimator.dvl_latency is how long before its stamp a DVL velocity was measured: 0 here, since the
    simulator stamps readings at acquisition and only delays their delivery by latency_s."""
    dvl = [s for s in resolved["robot"]["sensors"] if s["type"] == "reference_velocity"]
    if len(dvl) != 1:
        raise ValueError(f"expected one DVL (reference_velocity) sensor, found {len(dvl)}")
    out = json.loads(json.dumps(base))
    for node in out.values():
        node["ros__parameters"].setdefault("estimator", {})["dvl_latency"] = 0.0
    return out


def write(resolved_path, out_dir, descriptions_path, mpc_path):
    """Writes the three files into out_dir; returns their paths (vehicle, hydrodynamics, mpc params)."""
    resolved = json.loads(Path(resolved_path).read_text())
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    files = {
        "vehicle.yaml": vehicle(resolved, yaml.safe_load(Path(descriptions_path).read_text())),
        "hydrodynamics.yaml": hydrodynamics(resolved),
        "mpc.yaml": mpc_params(resolved, yaml.safe_load(Path(mpc_path).read_text())),
    }
    for name, data in files.items():
        (out / name).write_text(yaml.safe_dump(data, sort_keys=False, default_flow_style=None))
    return tuple(str(out / name) for name in files)


if __name__ == "__main__":
    if len(sys.argv) != 5:
        sys.exit(__doc__.strip().splitlines()[-1].strip())
    print("\n".join(write(*sys.argv[1:])))
