"""Standalone simulation; explicit stepping and copied, typed observations."""

from importlib import import_module
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ._native import (
        Ahrs,
        AhrsParameters,
        AhrsReading,
        AhrsSample,
        AhrsStream,
        AltitudeReading,
        AltitudeSample,
        AltitudeStream,
        Attitude,
        AttitudeParameters,
        AttitudeReading,
        AttitudeSample,
        AttitudeStream,
        BodyParameters,
        BodyState,
        BoxProxy,
        ContactModel,
        ContactParameters,
        Device,
        Dvl,
        DvlParameters,
        DvlReading,
        DvlSample,
        DvlStream,
        FixedFrame,
        FixedFrames,
        Fog,
        FogReading,
        FogSample,
        FogStream,
        HydrostaticPressure,
        Imu,
        ImuReading,
        ImuReporting,
        ImuSample,
        ImuStream,
        InclinationLimit,
        Mount,
        NoiseParameters,
        OverflowPolicy,
        PlantParameters,
        Pool,
        Pose,
        Pressure,
        PressureParameters,
        PressureReading,
        PressureSample,
        PressureStream,
        ReferenceAltitude,
        ReferenceAltitudeParameters,
        ReferenceVelocity,
        ReferenceVelocityParameters,
        Runtime,
        SampleHeader,
        ScalarNoiseParameters,
        Scenario,
        ScheduledCommand,
        SensorInfo,
        Snapshot,
        StreamStats,
        Thruster,
        VelocityReading,
        VelocitySample,
        VelocityStream,
        load_scenario,
    )


def example_scenario() -> Path:
    """Return the installed synthetic scenario and its relative profile tree."""
    return Path(__file__).resolve().parent / "content" / "examples" / "profile_pool.yaml"


__all__ = [
    "ReferenceAltitude",
    "ReferenceAltitudeParameters",
    "AltitudeReading",
    "AltitudeSample",
    "AltitudeStream",
    "InclinationLimit",
    "ReferenceVelocityParameters",
    "ReferenceVelocity",
    "VelocityReading",
    "VelocitySample",
    "VelocityStream",
    "Attitude",
    "AttitudeParameters",
    "AttitudeReading",
    "AttitudeSample",
    "AttitudeStream",
    "Ahrs",
    "AhrsParameters",
    "AhrsReading",
    "AhrsSample",
    "AhrsStream",
    "Pose",
    "FixedFrame",
    "FixedFrames",
    "BoxProxy",
    "ContactModel",
    "ContactParameters",
    "BodyState",
    "BodyParameters",
    "Pool",
    "Thruster",
    "PlantParameters",
    "Snapshot",
    "OverflowPolicy",
    "Device",
    "SampleHeader",
    "StreamStats",
    "Mount",
    "NoiseParameters",
    "ScalarNoiseParameters",
    "DvlParameters",
    "PressureParameters",
    "HydrostaticPressure",
    "Imu",
    "ImuReporting",
    "Fog",
    "Dvl",
    "Pressure",
    "ImuReading",
    "FogReading",
    "DvlReading",
    "PressureReading",
    "ImuSample",
    "FogSample",
    "DvlSample",
    "PressureSample",
    "ImuStream",
    "FogStream",
    "DvlStream",
    "PressureStream",
    "Runtime",
    "ScheduledCommand",
    "SensorInfo",
    "Scenario",
    "load_scenario",
    "example_scenario",
]


def __getattr__(name: str) -> Any:
    """Configuration tools do not need to import or build the native simulation module."""
    if name not in __all__:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module("._native", __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
