"""Standalone simulation; explicit stepping and copied, typed observations."""

from pathlib import Path

from ._native import (
    BodyParameters,
    BodyState,
    BoxProxy,
    ContactModel,
    ContactParameters,
    Device,
    Dvl,
    DvlParameters,
    DvlReading,
    DvlSample,
    DvlStream,
    FixedFrame,
    FixedFrames,
    Fog,
    FogReading,
    FogSample,
    FogStream,
    HydrostaticPressure,
    Imu,
    ImuReading,
    ImuReporting,
    ImuSample,
    ImuStream,
    Mount,
    NoiseParameters,
    OverflowPolicy,
    PlantParameters,
    Pool,
    Pose,
    Pressure,
    PressureParameters,
    PressureReading,
    PressureSample,
    PressureStream,
    Runtime,
    SampleHeader,
    ScalarNoiseParameters,
    Scenario,
    ScheduledCommand,
    SensorInfo,
    Snapshot,
    StreamStats,
    Thruster,
    load_scenario,
)


def example_scenario() -> Path:
    """Return the installed synthetic scenario and its relative profile tree."""
    return Path(__file__).resolve().parent / "content" / "examples" / "profile_pool.yaml"


__all__ = [
    "Pose",
    "FixedFrame",
    "FixedFrames",
    "BoxProxy",
    "ContactModel",
    "ContactParameters",
    "BodyState",
    "BodyParameters",
    "Pool",
    "Thruster",
    "PlantParameters",
    "Snapshot",
    "OverflowPolicy",
    "Device",
    "SampleHeader",
    "StreamStats",
    "Mount",
    "NoiseParameters",
    "ScalarNoiseParameters",
    "DvlParameters",
    "PressureParameters",
    "HydrostaticPressure",
    "Imu",
    "ImuReporting",
    "Fog",
    "Dvl",
    "Pressure",
    "ImuReading",
    "FogReading",
    "DvlReading",
    "PressureReading",
    "ImuSample",
    "FogSample",
    "DvlSample",
    "PressureSample",
    "ImuStream",
    "FogStream",
    "DvlStream",
    "PressureStream",
    "Runtime",
    "ScheduledCommand",
    "SensorInfo",
    "Scenario",
    "load_scenario",
    "example_scenario",
]
