"""Optional EGL camera capture; arrays retain their immutable native owners."""
from os import PathLike

import numpy as np
from numpy.typing import ArrayLike, NDArray

class Intrinsics:
    width: int
    height: int
    fx: float
    fy: float
    cx: float
    cy: float
    near_plane: float
    far_plane: float
    def __init__(self) -> None: ...
    def projection(self) -> NDArray[np.float32]: ...

def optical_view(position: ArrayLike, wxyz: ArrayLike) -> NDArray[np.float32]: ...

class DepthNoise:
    enabled: bool
    base_sigma: float
    range_sigma: float
    exponent: float
    min_range: float
    max_range: float
    bias: float
    dropout: float
    range_dropout: float
    edge_dropout: float
    outliers: float
    correlation: float
    patch_size: int
    def __init__(self) -> None: ...

class Frame:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rgb(self) -> NDArray[np.uint8]: ...
    @property
    def depth(self) -> NDArray[np.float32]: ...
    @property
    def jpeg(self) -> bytes: ...

class ImageCapture:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rgb(self) -> NDArray[np.uint8]: ...
    @property
    def depth(self) -> NDArray[np.float32]: ...

class Processor:
    def __init__(self, seed: int = 7) -> None: ...
    def reset(self, seed: int) -> None: ...
    def process(self, intrinsics: Intrinsics, noise: DepthNoise, input: ImageCapture,
                jpeg: bool = False, quality: int = 93) -> Frame: ...

class Mesh: ...
def load_mesh(path: str | PathLike[str]) -> Mesh: ...
def box_mesh() -> Mesh: ...

class SurfaceMaterial:
    ASSET: SurfaceMaterial
    TILES: SurfaceMaterial
    DECK: SurfaceMaterial
    LINER: SurfaceMaterial

class Instance:
    mesh: Mesh | None
    @property
    def transform(self) -> NDArray[np.float32]: ...
    @transform.setter
    def transform(self, value: ArrayLike) -> None: ...
    @property
    def tint(self) -> NDArray[np.float32]: ...
    @tint.setter
    def tint(self, value: ArrayLike) -> None: ...
    material: SurfaceMaterial
    visible: bool
    casts_shadow: bool
    def __init__(self) -> None: ...

class Scene:
    instances: list[Instance]  # Assign the full list; reading returns a copy.
    @property
    def lighting_center(self) -> NDArray[np.float32]: ...
    @lighting_center.setter
    def lighting_center(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...
    def add(self, instance: Instance) -> None: ...

class PoolGeometry:
    @property
    def dimensions(self) -> NDArray[np.float32]: ...
    @dimensions.setter
    def dimensions(self, value: ArrayLike) -> None: ...
    water_level: float
    deck_height: float
    @property
    def local_to_world(self) -> NDArray[np.float32]: ...
    @local_to_world.setter
    def local_to_world(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...

def pool_scene(geometry: PoolGeometry) -> Scene: ...

class View:
    @property
    def view(self) -> NDArray[np.float32]: ...
    @view.setter
    def view(self, value: ArrayLike) -> None: ...
    @property
    def projection(self) -> NDArray[np.float32]: ...
    @projection.setter
    def projection(self, value: ArrayLike) -> None: ...
    @property
    def eye(self) -> NDArray[np.float32]: ...
    @eye.setter
    def eye(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...

class WaterOptics:
    @property
    def tint(self) -> NDArray[np.float32]: ...
    @tint.setter
    def tint(self, value: ArrayLike) -> None: ...
    @property
    def absorption(self) -> NDArray[np.float32]: ...
    @absorption.setter
    def absorption(self, value: ArrayLike) -> None: ...
    scattering: float
    distance_scale: float
    distance_power: float
    clear_distance: float
    def __init__(self) -> None: ...

class Appearance:
    water: WaterOptics
    caustics: float
    exposure: float
    surface: bool
    shadows: bool
    reflections: bool
    outdoor: bool
    sun_azimuth: float
    sun_elevation: float
    direct_light: float
    ambient_light: float
    glare: float
    def __init__(self) -> None: ...

class OffscreenRenderer:
    def __init__(self, shader_directory: str | PathLike[str]) -> None: ...
    @property
    def device(self) -> str: ...
    def capture(self, scene: Scene, view: View, appearance: Appearance, time: float,
                width: int, height: int, color: bool = True, depth: bool = True) -> ImageCapture: ...
