"""Optional EGL camera capture; arrays retain their immutable native owners."""
from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

class Intrinsics:
    width: int
    height: int
    fx: float
    fy: float
    cx: float
    cy: float
    near_plane: float
    far_plane: float
    def __init__(self) -> None: ...
    def projection(self) -> NDArray[np.float32]: ...

class Pose:
    """rp_spatial pose; module-local twin of, and interoperable with, _native.Pose."""
    def __init__(self) -> None: ...
    def compose(self, child: Pose) -> Pose: ...
    def inverse(self) -> Pose: ...
    def apply(self, point: ArrayLike) -> NDArray[np.float64]: ...
    def matrix(self) -> NDArray[np.float64]: ...
    @property
    def translation(self) -> NDArray[np.float64]: ...
    @translation.setter
    def translation(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> NDArray[np.float64]: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class FixedFrame:
    def __init__(self) -> None: ...
    parent: str
    child: str
    @property
    def pose(self) -> Pose: ...
    @pose.setter
    def pose(self, value: Pose) -> None: ...

class FixedFrames:
    def __init__(self, root: str, edges: Sequence[FixedFrame]) -> None: ...
    @property
    def root(self) -> str: ...
    @property
    def edges(self) -> list[FixedFrame]: ...
    def from_root(self, frame: str) -> Pose: ...
    def lookup(self, target: str, from_frame: str) -> Pose: ...

@overload
def optical_view(position: ArrayLike, wxyz: ArrayLike) -> NDArray[np.float32]: ...
@overload
def optical_view(world_from_optical: Pose) -> NDArray[np.float32]: ...

class DepthNoise:
    enabled: bool
    base_sigma: float
    range_sigma: float
    exponent: float
    min_range: float
    max_range: float
    bias: float
    dropout: float
    range_dropout: float
    edge_dropout: float
    outliers: float
    correlation: float
    patch_size: int
    def __init__(self) -> None: ...

class Frame:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rgb(self) -> NDArray[np.uint8]: ...
    @property
    def depth(self) -> NDArray[np.float32]: ...
    @property
    def jpeg(self) -> bytes: ...

class ImageCapture:
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rgb(self) -> NDArray[np.uint8]: ...
    @property
    def depth(self) -> NDArray[np.float32]: ...

class Processor:
    def __init__(self, seed: int = 7) -> None: ...
    def reset(self, seed: int) -> None: ...
    def process(self, intrinsics: Intrinsics, noise: DepthNoise, input: ImageCapture,
                jpeg: bool = False, quality: int = 93) -> Frame: ...

class Mesh:
    @property
    def dependencies(self) -> list[Path]: ...
    @property
    def textures(self) -> list[Path]: ...
    def with_texture(self, texture: str | PathLike[str]) -> Mesh: ...
def load_mesh(path: str | PathLike[str]) -> Mesh: ...
def perforate_mesh(mesh: Mesh, asset_to_panel: ArrayLike, faces_x: Sequence[float],
                   half_size: float, cutouts: Sequence[tuple[float, float, float]],
                   tolerance: float = 5e-4) -> tuple[Mesh, list[int]]: ...
def box_mesh() -> Mesh: ...

class SurfaceMaterial:
    ASSET: SurfaceMaterial
    TILES: SurfaceMaterial
    DECK: SurfaceMaterial
    LINER: SurfaceMaterial

class Instance:
    mesh: Mesh | None
    @property
    def transform(self) -> NDArray[np.float32]: ...
    @transform.setter
    def transform(self, value: ArrayLike) -> None: ...
    @property
    def tint(self) -> NDArray[np.float32]: ...
    @tint.setter
    def tint(self, value: ArrayLike) -> None: ...
    material: SurfaceMaterial
    visible: bool
    casts_shadow: bool
    def __init__(self) -> None: ...

class Scene:
    instances: list[Instance]  # Assign the full list; reading returns a copy.
    @property
    def lighting_center(self) -> NDArray[np.float32]: ...
    @lighting_center.setter
    def lighting_center(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...
    def add(self, instance: Instance) -> None: ...

class PoolGeometry:
    @property
    def dimensions(self) -> NDArray[np.float32]: ...
    @dimensions.setter
    def dimensions(self, value: ArrayLike) -> None: ...
    water_level: float
    deck_height: float
    @property
    def local_to_world(self) -> NDArray[np.float32]: ...
    @local_to_world.setter
    def local_to_world(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...

def pool_scene(geometry: PoolGeometry) -> Scene: ...

class View:
    @property
    def view(self) -> NDArray[np.float32]: ...
    @view.setter
    def view(self, value: ArrayLike) -> None: ...
    @property
    def projection(self) -> NDArray[np.float32]: ...
    @projection.setter
    def projection(self, value: ArrayLike) -> None: ...
    @property
    def eye(self) -> NDArray[np.float32]: ...
    @eye.setter
    def eye(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...

class WaterOptics:
    @property
    def tint(self) -> NDArray[np.float32]: ...
    @tint.setter
    def tint(self, value: ArrayLike) -> None: ...
    @property
    def absorption(self) -> NDArray[np.float32]: ...
    @absorption.setter
    def absorption(self, value: ArrayLike) -> None: ...
    scattering: float
    distance_scale: float
    distance_power: float
    clear_distance: float
    def __init__(self) -> None: ...

class Appearance:
    water: WaterOptics
    caustics: float
    exposure: float
    surface: bool
    shadows: bool
    reflections: bool
    outdoor: bool
    sun_azimuth: float
    sun_elevation: float
    direct_light: float
    ambient_light: float
    glare: float
    def __init__(self) -> None: ...

class OffscreenRenderer:
    def __init__(self, shader_directory: str | PathLike[str]) -> None: ...
    @property
    def device(self) -> str: ...
    def capture(self, scene: Scene, view: View, appearance: Appearance, time: float,
                width: int, height: int, color: bool = True, depth: bool = True) -> ImageCapture: ...
