from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import ClassVar, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

FloatArray = NDArray[np.float64]

class Pose:
    def __init__(self) -> None: ...
    def compose(self, child: Pose) -> Pose: ...
    def inverse(self) -> Pose: ...
    def apply(self, point: ArrayLike) -> FloatArray: ...
    @property
    def translation(self) -> FloatArray: ...
    @translation.setter
    def translation(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class FixedFrame:
    def __init__(self) -> None: ...
    parent: str
    child: str
    @property
    def pose(self) -> Pose: ...
    @pose.setter
    def pose(self, value: Pose) -> None: ...

class FixedFrames:
    def __init__(self, root: str, edges: Sequence[FixedFrame]) -> None: ...
    @property
    def root(self) -> str: ...
    @property
    def edges(self) -> list[FixedFrame]: ...
    def from_root(self, frame: str) -> Pose: ...
    def lookup(self, target: str, from_frame: str) -> Pose: ...

class ContactModel:
    DISABLED: ClassVar[ContactModel]
    SPHERE_POOL: ClassVar[ContactModel]
    BOX_SCENE: ClassVar[ContactModel]

class BoxProxy:
    def __init__(self) -> None: ...
    id: str
    @property
    def size(self) -> FloatArray: ...
    @size.setter
    def size(self, value: ArrayLike) -> None: ...
    @property
    def center(self) -> FloatArray: ...
    @center.setter
    def center(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class ContactParameters:
    def __init__(self) -> None: ...
    model: ContactModel
    restitution: float
    friction: float
    @property
    def body_boxes(self) -> list[BoxProxy]: ...
    @body_boxes.setter
    def body_boxes(self, value: Sequence[BoxProxy]) -> None: ...
    @property
    def world_boxes(self) -> list[BoxProxy]: ...
    @world_boxes.setter
    def world_boxes(self, value: Sequence[BoxProxy]) -> None: ...

class BodyState:
    def __init__(self) -> None: ...
    @property
    def position(self) -> FloatArray: ...
    @position.setter
    def position(self, value: ArrayLike) -> None: ...
    @property
    def linear_velocity(self) -> FloatArray: ...
    @linear_velocity.setter
    def linear_velocity(self, value: ArrayLike) -> None: ...
    @property
    def angular_velocity(self) -> FloatArray: ...
    @angular_velocity.setter
    def angular_velocity(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class BodyParameters:
    def __init__(self) -> None: ...
    mass: float
    displaced_volume: float
    collision_radius: float
    @property
    def inertia(self) -> FloatArray: ...
    @inertia.setter
    def inertia(self, value: ArrayLike) -> None: ...
    @property
    def added_mass(self) -> FloatArray: ...
    @added_mass.setter
    def added_mass(self, value: ArrayLike) -> None: ...
    @property
    def linear_damping(self) -> FloatArray: ...
    @linear_damping.setter
    def linear_damping(self, value: ArrayLike) -> None: ...
    @property
    def quadratic_damping(self) -> FloatArray: ...
    @quadratic_damping.setter
    def quadratic_damping(self, value: ArrayLike) -> None: ...
    @property
    def damping_center(self) -> FloatArray: ...
    @damping_center.setter
    def damping_center(self, value: ArrayLike) -> None: ...
    @property
    def buoyancy_center(self) -> FloatArray: ...
    @buoyancy_center.setter
    def buoyancy_center(self, value: ArrayLike) -> None: ...
    @property
    def buoyancy_radii(self) -> FloatArray: ...
    @buoyancy_radii.setter
    def buoyancy_radii(self, value: ArrayLike) -> None: ...

class Pool:
    yaw_world: float
    @property
    def origin_xy_world(self) -> FloatArray: ...
    @origin_xy_world.setter
    def origin_xy_world(self, value: ArrayLike) -> None: ...
    current_oscillation_frequency: float
    @property
    def current_oscillation_amplitude(self) -> FloatArray: ...
    @current_oscillation_amplitude.setter
    def current_oscillation_amplitude(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...
    length: float
    width: float
    depth: float
    water_level: float
    water_density: float
    @property
    def current_velocity(self) -> FloatArray: ...
    @current_velocity.setter
    def current_velocity(self, value: ArrayLike) -> None: ...

class Thruster:
    deadband: float
    forward_scale: float
    reverse_scale: float
    efficiency: float
    propeller_radius: float | None
    def __init__(self) -> None: ...
    delay: float
    rise_time: float
    fall_time: float
    slew_rate: float
    forward_limit: float
    reverse_limit: float
    @property
    def position(self) -> FloatArray: ...
    @position.setter
    def position(self, value: ArrayLike) -> None: ...
    @property
    def direction(self) -> FloatArray: ...
    @direction.setter
    def direction(self, value: ArrayLike) -> None: ...
    id: str

class PlantParameters:
    def __init__(self) -> None: ...
    command_timeout: float
    body: BodyParameters
    pool: Pool
    contacts: ContactParameters
    timestep_ns: int
    @property
    def thrusters(self) -> list[Thruster]: ...
    @thrusters.setter
    def thrusters(self, value: Sequence[Thruster]) -> None: ...

class Mount:
    def __init__(self) -> None: ...
    @property
    def position_body(self) -> FloatArray: ...
    @position_body.setter
    def position_body(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class NoiseParameters:
    def __init__(self) -> None: ...
    @property
    def bias(self) -> FloatArray: ...
    @bias.setter
    def bias(self, value: ArrayLike) -> None: ...
    @property
    def white_stddev(self) -> FloatArray: ...
    @white_stddev.setter
    def white_stddev(self, value: ArrayLike) -> None: ...
    @property
    def walk_stddev(self) -> FloatArray: ...
    @walk_stddev.setter
    def walk_stddev(self, value: ArrayLike) -> None: ...

class ScalarNoiseParameters:
    def __init__(self) -> None: ...
    bias: float
    white_stddev: float
    walk_stddev: float

class DvlParameters:
    def __init__(self) -> None: ...
    minimum_range: float
    maximum_range: float
    @property
    def bottom_axis(self) -> FloatArray: ...
    @bottom_axis.setter
    def bottom_axis(self, value: ArrayLike) -> None: ...
    mount: Mount
    velocity_noise: NoiseParameters

class PressureParameters:
    def __init__(self) -> None: ...
    reference_pressure: float
    reference_density: float
    reference_gravity: float
    minimum_pressure: float
    maximum_pressure: float
    mount: Mount
    noise: ScalarNoiseParameters

class Snapshot:
    @property
    def generation(self) -> int: ...
    @property
    def tick(self) -> int: ...
    @property
    def elapsed_ns(self) -> int: ...
    @property
    def body(self) -> BodyState: ...
    @property
    def thruster_forces(self) -> FloatArray: ...

class OverflowPolicy:
    FAIL: ClassVar[OverflowPolicy]
    DROP_OLDEST: ClassVar[OverflowPolicy]
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Device:
    def __init__(
        self,
        id: str,
        frame: str,
        period_ns: int = ...,
        latency_ns: int = ...,
        capacity: int = ...,
        overflow: OverflowPolicy = ...,
    ) -> None: ...
    id: str
    frame: str
    period_ns: int
    latency_ns: int
    capacity: int
    overflow: OverflowPolicy

class SampleHeader:
    @property
    def device_id(self) -> str: ...
    @property
    def frame(self) -> str: ...
    @property
    def generation(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def tick(self) -> int: ...
    @property
    def scheduled_ns(self) -> int: ...
    @property
    def acquired_ns(self) -> int: ...
    @property
    def delivered_ns(self) -> int: ...

class StreamStats:
    @property
    def acquired(self) -> int: ...
    @property
    def delivered(self) -> int: ...
    @property
    def unavailable(self) -> int: ...
    @property
    def dropped_pending(self) -> int: ...
    @property
    def dropped_delivered(self) -> int: ...

class HydrostaticPressure:
    def __init__(
        self,
        water_level: float,
        density: float = ...,
        surface_pressure: float = ...,
        gravity: float = ...,
    ) -> None: ...

class ImuReporting:
    def __init__(self) -> None: ...
    gravity_magnitude: float | None
    @property
    def force_variance(self) -> FloatArray | None: ...
    @force_variance.setter
    def force_variance(self, value: ArrayLike | None) -> None: ...
    @property
    def angular_variance(self) -> FloatArray | None: ...
    @angular_variance.setter
    def angular_variance(self, value: ArrayLike | None) -> None: ...

class Imu:
    def __init__(
        self,
        mount: Mount = ...,
        acceleration_noise: NoiseParameters = ...,
        gyro_noise: NoiseParameters = ...,
        reporting: ImuReporting = ...,
    ) -> None: ...

class AttitudeParameters:
    def __init__(self) -> None: ...
    angle_stddev: float
    heading_drift_rate: float
    @property
    def heading_axis_world(self) -> FloatArray: ...
    @heading_axis_world.setter
    def heading_axis_world(self, value: ArrayLike) -> None: ...
    @property
    def reported_variance(self) -> FloatArray | None: ...
    @reported_variance.setter
    def reported_variance(self, value: ArrayLike | None) -> None: ...

class AhrsParameters:
    def __init__(self) -> None: ...
    acceleration_noise: NoiseParameters
    gyro_noise: NoiseParameters
    inertial_reporting: ImuReporting
    attitude: AttitudeParameters

class Attitude:
    def __init__(self, mount: Mount = ..., parameters: AttitudeParameters = ...) -> None: ...

class Ahrs:
    def __init__(self, mount: Mount = ..., parameters: AhrsParameters = ...) -> None: ...

class Fog:
    def __init__(
        self,
        mount: Mount = ...,
        axes: Sequence[ArrayLike] = ...,
        gyro_noise: NoiseParameters = ...,
        reported_variance: ArrayLike | None = ...,
    ) -> None: ...

class InclinationLimit:
    def __init__(self) -> None: ...
    maximum_angle: float
    @property
    def sensor_axis(self) -> FloatArray: ...
    @sensor_axis.setter
    def sensor_axis(self, value: ArrayLike) -> None: ...
    @property
    def reference_axis_world(self) -> FloatArray: ...
    @reference_axis_world.setter
    def reference_axis_world(self, value: ArrayLike) -> None: ...

class ReferenceVelocityParameters:
    def __init__(self) -> None: ...
    mount: Mount
    noise: NoiseParameters
    inclination_limit: InclinationLimit | None
    @property
    def reference_velocity_world(self) -> FloatArray: ...
    @reference_velocity_world.setter
    def reference_velocity_world(self, value: ArrayLike) -> None: ...
    @property
    def reported_variance(self) -> FloatArray | None: ...
    @reported_variance.setter
    def reported_variance(self, value: ArrayLike | None) -> None: ...

class ReferenceVelocity:
    def __init__(self, parameters: ReferenceVelocityParameters = ...) -> None: ...

class VelocityReading:
    @property
    def reference_relative_velocity(self) -> FloatArray: ...
    @property
    def covariance(self) -> FloatArray: ...

class VelocitySample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> VelocityReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class VelocityStream:
    def latest(self) -> VelocitySample | None: ...
    def drain(self) -> list[VelocitySample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class Dvl:
    def __init__(self, parameters: DvlParameters, pool: Pool) -> None: ...

class ReferenceAltitudeParameters:
    def __init__(self) -> None: ...
    mount: Mount
    noise: ScalarNoiseParameters
    reported_variance: float | None
    @property
    def target_position_body(self) -> FloatArray | None: ...
    @target_position_body.setter
    def target_position_body(self, value: ArrayLike | None) -> None: ...

class ReferenceAltitude:
    def __init__(self, parameters: ReferenceAltitudeParameters = ...) -> None: ...

class AltitudeReading:
    @property
    def mounted_world_z(self) -> float: ...
    @property
    def target_world_z(self) -> float: ...
    @property
    def variance(self) -> float: ...

class AltitudeSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> AltitudeReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class AltitudeStream:
    def latest(self) -> AltitudeSample | None: ...
    def drain(self) -> list[AltitudeSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class Pressure:
    def __init__(
        self, parameters: PressureParameters, environment: HydrostaticPressure
    ) -> None: ...

class ImuReading:
    @property
    def specific_force(self) -> FloatArray: ...
    @property
    def angular_velocity(self) -> FloatArray: ...
    @property
    def force_covariance(self) -> FloatArray: ...
    @property
    def angular_covariance(self) -> FloatArray: ...

class ImuSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> ImuReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class ImuStream:
    def latest(self) -> ImuSample | None: ...
    def drain(self) -> list[ImuSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class AttitudeReading:
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @property
    def covariance(self) -> FloatArray: ...

class AhrsReading:
    @property
    def inertial(self) -> ImuReading: ...
    @property
    def attitude(self) -> AttitudeReading: ...

class AttitudeSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> AttitudeReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class AttitudeStream:
    def latest(self) -> AttitudeSample | None: ...
    def drain(self) -> list[AttitudeSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class AhrsSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> AhrsReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class AhrsStream:
    def latest(self) -> AhrsSample | None: ...
    def drain(self) -> list[AhrsSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class FogReading:
    @property
    def angular_rates(self) -> FloatArray: ...
    @property
    def covariance(self) -> FloatArray: ...

class FogSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> FogReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class FogStream:
    def latest(self) -> FogSample | None: ...
    def drain(self) -> list[FogSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class DvlReading:
    @property
    def bottom_relative_velocity(self) -> FloatArray: ...
    @property
    def covariance(self) -> FloatArray: ...
    @property
    def bottom_distance(self) -> float: ...

class DvlSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> DvlReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class DvlStream:
    def latest(self) -> DvlSample | None: ...
    def drain(self) -> list[DvlSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class PressureReading:
    @property
    def absolute_pressure(self) -> float: ...
    @property
    def pressure_variance(self) -> float: ...
    @property
    def depth(self) -> float: ...
    @property
    def depth_variance(self) -> float: ...

class PressureSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> PressureReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class PressureStream:
    def latest(self) -> PressureSample | None: ...
    def drain(self) -> list[PressureSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class Runtime:
    def __init__(
        self, parameters: PlantParameters, initial: BodyState, seed: int = ...
    ) -> None: ...
    def command(self, forces: ArrayLike) -> None: ...
    def stop_thrusters(self) -> None: ...
    def advance(self, ticks: int = ...) -> Snapshot: ...
    def observe(self) -> Snapshot: ...
    def place(self, state: BodyState, clear_actuators: bool = ...) -> Snapshot: ...
    def reset(self, initial: BodyState, seed: int) -> Snapshot: ...
    @property
    def faulted(self) -> bool: ...
    def imu_stream(self, id: str) -> ImuStream: ...
    def attitude_stream(self, id: str) -> AttitudeStream: ...
    def ahrs_stream(self, id: str) -> AhrsStream: ...
    def fog_stream(self, id: str) -> FogStream: ...
    def dvl_stream(self, id: str) -> DvlStream: ...
    def velocity_stream(self, id: str) -> VelocityStream: ...
    def altitude_stream(self, id: str) -> AltitudeStream: ...
    def pressure_stream(self, id: str) -> PressureStream: ...
    @overload
    def add(self, device: Device, model: Imu) -> ImuStream: ...
    @overload
    def add(self, device: Device, model: Attitude) -> AttitudeStream: ...
    @overload
    def add(self, device: Device, model: Ahrs) -> AhrsStream: ...
    @overload
    def add(self, device: Device, model: Fog) -> FogStream: ...
    @overload
    def add(self, device: Device, model: ReferenceVelocity) -> VelocityStream: ...
    @overload
    def add(self, device: Device, model: Dvl) -> DvlStream: ...
    @overload
    def add(self, device: Device, model: ReferenceAltitude) -> AltitudeStream: ...
    @overload
    def add(self, device: Device, model: Pressure) -> PressureStream: ...

class ScheduledCommand:
    @property
    def tick(self) -> int: ...
    @property
    def forces(self) -> FloatArray: ...

class SensorInfo:
    @property
    def device(self) -> Device: ...
    @property
    def model(self) -> str: ...

class Scenario:
    @property
    def body_frames(self) -> FixedFrames: ...
    @property
    def plant(self) -> PlantParameters: ...
    @property
    def initial(self) -> BodyState: ...
    @property
    def seed(self) -> int: ...
    @property
    def ticks(self) -> int: ...
    @property
    def surface_pressure(self) -> float: ...
    @property
    def commands(self) -> list[ScheduledCommand]: ...
    @property
    def sources(self) -> list[Path]: ...
    @property
    def sensors(self) -> list[SensorInfo]: ...
    def create_runtime(
        self, initial: BodyState | None = ..., seed: int | None = ...
    ) -> Runtime: ...

def load_scenario(path: str | PathLike[str]) -> Scenario: ...

class PayloadModel:
    FIXED_AXIS: ClassVar[PayloadModel]
    FINNED: ClassVar[PayloadModel]

class PayloadParameters:
    def __init__(self) -> None: ...
    model: PayloadModel
    mass: float
    displaced_volume: float
    neutral_buoyancy: bool
    added_mass: float
    length: float
    radius: float
    drag_axial: float
    drag_lateral: float
    center_of_mass: float
    center_of_buoyancy: float
    center_of_drag: float
    angular_damping: float
    spring_energy: float

class PayloadState:
    def __init__(self) -> None: ...
    @property
    def position(self) -> FloatArray: ...
    @position.setter
    def position(self, value: ArrayLike) -> None: ...
    @property
    def velocity(self) -> FloatArray: ...
    @velocity.setter
    def velocity(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...
    @property
    def angular_velocity(self) -> FloatArray: ...
    @angular_velocity.setter
    def angular_velocity(self, value: ArrayLike) -> None: ...

class PayloadEnvironment:
    def __init__(self) -> None: ...
    water_density: float
    water_level: float
    @property
    def water_velocity(self) -> FloatArray: ...
    @water_velocity.setter
    def water_velocity(self, value: ArrayLike) -> None: ...

class PayloadDynamics:
    def __init__(self, parameters: PayloadParameters) -> None: ...
    @property
    def parameters(self) -> PayloadParameters: ...
    def advance(self, state: PayloadState, environment: PayloadEnvironment, dt_s: float) -> PayloadState: ...
    def launch_speed(self, environment: PayloadEnvironment) -> float: ...
    def support_extent(self, axis: ArrayLike) -> FloatArray: ...
