from collections.abc import Sequence
from os import PathLike
from pathlib import Path
from typing import ClassVar, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

FloatArray = NDArray[np.float64]

class BodyState:
    def __init__(self) -> None: ...
    @property
    def position(self) -> FloatArray: ...
    @position.setter
    def position(self, value: ArrayLike) -> None: ...
    @property
    def linear_velocity(self) -> FloatArray: ...
    @linear_velocity.setter
    def linear_velocity(self, value: ArrayLike) -> None: ...
    @property
    def angular_velocity(self) -> FloatArray: ...
    @angular_velocity.setter
    def angular_velocity(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class BodyParameters:
    def __init__(self) -> None: ...
    mass: float
    displaced_volume: float
    collision_radius: float
    @property
    def inertia(self) -> FloatArray: ...
    @inertia.setter
    def inertia(self, value: ArrayLike) -> None: ...
    @property
    def added_mass(self) -> FloatArray: ...
    @added_mass.setter
    def added_mass(self, value: ArrayLike) -> None: ...
    @property
    def linear_damping(self) -> FloatArray: ...
    @linear_damping.setter
    def linear_damping(self, value: ArrayLike) -> None: ...
    @property
    def quadratic_damping(self) -> FloatArray: ...
    @quadratic_damping.setter
    def quadratic_damping(self, value: ArrayLike) -> None: ...
    @property
    def damping_center(self) -> FloatArray: ...
    @damping_center.setter
    def damping_center(self, value: ArrayLike) -> None: ...
    @property
    def buoyancy_center(self) -> FloatArray: ...
    @buoyancy_center.setter
    def buoyancy_center(self, value: ArrayLike) -> None: ...
    @property
    def buoyancy_radii(self) -> FloatArray: ...
    @buoyancy_radii.setter
    def buoyancy_radii(self, value: ArrayLike) -> None: ...

class Pool:
    current_oscillation_frequency: float
    @property
    def current_oscillation_amplitude(self) -> FloatArray: ...
    @current_oscillation_amplitude.setter
    def current_oscillation_amplitude(self, value: ArrayLike) -> None: ...
    def __init__(self) -> None: ...
    length: float
    width: float
    depth: float
    water_level: float
    water_density: float
    @property
    def current_velocity(self) -> FloatArray: ...
    @current_velocity.setter
    def current_velocity(self, value: ArrayLike) -> None: ...

class Thruster:
    deadband: float
    forward_scale: float
    reverse_scale: float
    efficiency: float
    propeller_radius: float | None
    def __init__(self) -> None: ...
    delay: float
    rise_time: float
    fall_time: float
    slew_rate: float
    forward_limit: float
    reverse_limit: float
    @property
    def position(self) -> FloatArray: ...
    @position.setter
    def position(self, value: ArrayLike) -> None: ...
    @property
    def direction(self) -> FloatArray: ...
    @direction.setter
    def direction(self, value: ArrayLike) -> None: ...
    id: str

class PlantParameters:
    def __init__(self) -> None: ...
    command_timeout: float
    body: BodyParameters
    pool: Pool
    timestep_ns: int
    @property
    def thrusters(self) -> list[Thruster]: ...
    @thrusters.setter
    def thrusters(self, value: Sequence[Thruster]) -> None: ...

class Mount:
    def __init__(self) -> None: ...
    @property
    def position_body(self) -> FloatArray: ...
    @position_body.setter
    def position_body(self, value: ArrayLike) -> None: ...
    @property
    def orientation_wxyz(self) -> FloatArray: ...
    @orientation_wxyz.setter
    def orientation_wxyz(self, value: ArrayLike) -> None: ...

class NoiseParameters:
    def __init__(self) -> None: ...
    @property
    def bias(self) -> FloatArray: ...
    @bias.setter
    def bias(self, value: ArrayLike) -> None: ...
    @property
    def white_stddev(self) -> FloatArray: ...
    @white_stddev.setter
    def white_stddev(self, value: ArrayLike) -> None: ...
    @property
    def walk_stddev(self) -> FloatArray: ...
    @walk_stddev.setter
    def walk_stddev(self, value: ArrayLike) -> None: ...

class ScalarNoiseParameters:
    def __init__(self) -> None: ...
    bias: float
    white_stddev: float
    walk_stddev: float

class DvlParameters:
    def __init__(self) -> None: ...
    minimum_range: float
    maximum_range: float
    @property
    def bottom_axis(self) -> FloatArray: ...
    @bottom_axis.setter
    def bottom_axis(self, value: ArrayLike) -> None: ...
    mount: Mount
    velocity_noise: NoiseParameters

class PressureParameters:
    def __init__(self) -> None: ...
    reference_pressure: float
    reference_density: float
    reference_gravity: float
    minimum_pressure: float
    maximum_pressure: float
    mount: Mount
    noise: ScalarNoiseParameters

class Snapshot:
    @property
    def generation(self) -> int: ...
    @property
    def tick(self) -> int: ...
    @property
    def elapsed_ns(self) -> int: ...
    @property
    def body(self) -> BodyState: ...
    @property
    def thruster_forces(self) -> FloatArray: ...

class OverflowPolicy:
    FAIL: ClassVar[OverflowPolicy]
    DROP_OLDEST: ClassVar[OverflowPolicy]
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Device:
    def __init__(
        self,
        id: str,
        frame: str,
        period_ns: int = ...,
        latency_ns: int = ...,
        capacity: int = ...,
        overflow: OverflowPolicy = ...,
    ) -> None: ...
    id: str
    frame: str
    period_ns: int
    latency_ns: int
    capacity: int
    overflow: OverflowPolicy

class SampleHeader:
    @property
    def device_id(self) -> str: ...
    @property
    def frame(self) -> str: ...
    @property
    def generation(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def tick(self) -> int: ...
    @property
    def scheduled_ns(self) -> int: ...
    @property
    def acquired_ns(self) -> int: ...
    @property
    def delivered_ns(self) -> int: ...

class StreamStats:
    @property
    def acquired(self) -> int: ...
    @property
    def delivered(self) -> int: ...
    @property
    def unavailable(self) -> int: ...
    @property
    def dropped_pending(self) -> int: ...
    @property
    def dropped_delivered(self) -> int: ...

class HydrostaticPressure:
    def __init__(
        self,
        water_level: float,
        density: float = ...,
        surface_pressure: float = ...,
        gravity: float = ...,
    ) -> None: ...

class Imu:
    def __init__(
        self,
        mount: Mount = ...,
        acceleration_noise: NoiseParameters = ...,
        gyro_noise: NoiseParameters = ...,
    ) -> None: ...

class Fog:
    def __init__(
        self, mount: Mount = ..., axes: Sequence[ArrayLike] = ..., gyro_noise: NoiseParameters = ...
    ) -> None: ...

class Dvl:
    def __init__(self, parameters: DvlParameters, pool: Pool) -> None: ...

class Pressure:
    def __init__(
        self, parameters: PressureParameters, environment: HydrostaticPressure
    ) -> None: ...

class ImuReading:
    @property
    def specific_force(self) -> FloatArray: ...
    @property
    def angular_velocity(self) -> FloatArray: ...
    @property
    def force_covariance(self) -> FloatArray: ...
    @property
    def angular_covariance(self) -> FloatArray: ...

class ImuSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> ImuReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class ImuStream:
    def latest(self) -> ImuSample | None: ...
    def drain(self) -> list[ImuSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class FogReading:
    @property
    def angular_rates(self) -> FloatArray: ...
    @property
    def covariance(self) -> FloatArray: ...

class FogSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> FogReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class FogStream:
    def latest(self) -> FogSample | None: ...
    def drain(self) -> list[FogSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class DvlReading:
    @property
    def bottom_relative_velocity(self) -> FloatArray: ...
    @property
    def covariance(self) -> FloatArray: ...
    @property
    def bottom_distance(self) -> float: ...

class DvlSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> DvlReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class DvlStream:
    def latest(self) -> DvlSample | None: ...
    def drain(self) -> list[DvlSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class PressureReading:
    @property
    def absolute_pressure(self) -> float: ...
    @property
    def pressure_variance(self) -> float: ...
    @property
    def depth(self) -> float: ...
    @property
    def depth_variance(self) -> float: ...

class PressureSample:
    @property
    def header(self) -> SampleHeader: ...
    @property
    def value(self) -> PressureReading | None: ...
    @property
    def unavailable_reason(self) -> str: ...

class PressureStream:
    def latest(self) -> PressureSample | None: ...
    def drain(self) -> list[PressureSample]: ...
    @property
    def active(self) -> bool: ...
    @property
    def stats(self) -> StreamStats: ...

class Runtime:
    def __init__(
        self, parameters: PlantParameters, initial: BodyState, seed: int = ...
    ) -> None: ...
    def command(self, forces: ArrayLike) -> None: ...
    def stop_thrusters(self) -> None: ...
    def advance(self, ticks: int = ...) -> Snapshot: ...
    def observe(self) -> Snapshot: ...
    def reset(self, initial: BodyState, seed: int) -> Snapshot: ...
    @property
    def faulted(self) -> bool: ...
    def imu_stream(self, id: str) -> ImuStream: ...
    def fog_stream(self, id: str) -> FogStream: ...
    def dvl_stream(self, id: str) -> DvlStream: ...
    def pressure_stream(self, id: str) -> PressureStream: ...
    @overload
    def add(self, device: Device, model: Imu) -> ImuStream: ...
    @overload
    def add(self, device: Device, model: Fog) -> FogStream: ...
    @overload
    def add(self, device: Device, model: Dvl) -> DvlStream: ...
    @overload
    def add(self, device: Device, model: Pressure) -> PressureStream: ...

class ScheduledCommand:
    @property
    def tick(self) -> int: ...
    @property
    def forces(self) -> FloatArray: ...

class SensorInfo:
    @property
    def device(self) -> Device: ...
    @property
    def model(self) -> str: ...

class Scenario:
    @property
    def plant(self) -> PlantParameters: ...
    @property
    def initial(self) -> BodyState: ...
    @property
    def seed(self) -> int: ...
    @property
    def ticks(self) -> int: ...
    @property
    def surface_pressure(self) -> float: ...
    @property
    def commands(self) -> list[ScheduledCommand]: ...
    @property
    def sources(self) -> list[Path]: ...
    @property
    def sensors(self) -> list[SensorInfo]: ...
    def create_runtime(
        self, initial: BodyState | None = ..., seed: int | None = ...
    ) -> Runtime: ...

def load_scenario(path: str | PathLike[str]) -> Scenario: ...
