#!/usr/bin/env python3
"""Offline pinned Talos/pool conversion. Requires PyYAML; never used by the runtime."""

import argparse
import hashlib
import json
import math
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

import yaml
from capture_stage_reference import REVISION, ROOT

VEHICLE_REVISION = "7f37bdd62ab90113844137a23806c89b23a8ab9b"


def quaternion(rpy):
    sr, sp, sy = [math.sin(angle / 2) for angle in rpy]
    cr, cp, cy = [math.cos(angle / 2) for angle in rpy]
    values = [
        cr * cp * cy + sr * sp * sy,
        sr * cp * cy - cr * sp * sy,
        cr * sp * cy + sr * cp * sy,
        cr * cp * sy - sr * sp * cy,
    ]
    norm = math.sqrt(sum(value * value for value in values))
    return [value / norm for value in values]


def box(name, size, center, orientation=None):
    return {
        "id": name,
        "size_m": size,
        "center_m": center,
        "orientation_wxyz": orientation or [1, 0, 0, 0],
    }


def frame(parent, name, position, orientation=None):
    return {
        "parent": parent,
        "child": name,
        "position_m": position,
        "orientation_wxyz": orientation or [1, 0, 0, 0],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("simulator_repo", type=Path)
    parser.add_argument("vehicle_repo", type=Path)
    parser.add_argument(
        "--check", action="store_true", help="verify generated bytes without writes"
    )
    args = parser.parse_args()
    sources = {}

    def read(repo, revision, name):
        data = subprocess.check_output(["git", "-C", str(repo), "show", f"{revision}:{name}"])
        sources[f"{revision}:{name}"] = hashlib.sha256(data).hexdigest()
        return data

    def sim(name):
        return read(args.simulator_repo, REVISION, name)

    vehicle = yaml.safe_load(
        read(args.vehicle_repo, VEHICLE_REVISION, "riptide_descriptions/config/talos.yaml")
    )
    sensor_properties = yaml.safe_load(
        read(args.vehicle_repo, VEHICLE_REVISION, "riptide_descriptions/config/simulator.yaml")
    )["sensor_properties"]
    sensor_overrides = yaml.safe_load(sim("c_simulator/robots/talos/config/sensors.yaml"))[
        "/**/physics_simulator"
    ]["ros__parameters"]
    hydro = yaml.safe_load(sim("c_simulator/robots/talos/config/hydrodynamics.yaml"))
    world = yaml.safe_load(sim("c_simulator/worlds/competition_pool.yaml"))
    mapping = yaml.safe_load(sim("c_simulator/tasks/2026/config/mapping.yaml"))
    collision = ET.fromstring(sim("c_simulator/collision_files/robots/talos.urdf"))
    # Record the geometry/coordinate formula sources as well as their input data.
    physics_source = sim("c_simulator/src/physics_simulator.cpp").decode()
    # These defaults live in original node construction rather than YAML. Guard
    # their exact source definitions instead of treating them as platform defaults.
    for expression in (
        'gyroRate = declare_parameter<double>("gyro_rate", 500.0);',
        'gyroSigma = declare_parameter<double>("gyro_noise_stddev", 0.01 * M_PI / 180.0);',
        'gyroVariance = declare_parameter<double>("gyro_variance", std::max(1e-9, gyroSigma * gyroSigma));',
    ):
        if expression not in physics_source:
            raise ValueError("unexpected original FOG defaults")
    sim("c_simulator/src/robot_class.cpp")
    if hydro["schema_version"] != 1 or world["schema_version"] != 1 or hydro["robot"] != "talos":
        raise ValueError("unexpected pinned hydro/world schema or robot identity")
    com = vehicle["com"]
    dynamics = hydro["thruster_dynamics"]
    body = {
        "mass_kg": vehicle["mass"],
        "inertia_matrix": [hydro["rigid_body_inertia3x3"][i : i + 3] for i in (0, 3, 6)],
        "added_mass_matrix": hydro["added_mass6x6"],
        "linear_damping_matrix": hydro["linear_damping6x6"],
        "quadratic_damping": hydro["quadratic_damping"],
        "damping_center_m": hydro["damping_center_relative"],
        "displaced_volume_m3": hydro["displaced_volume"],
        "buoyancy_center_m": hydro["cob_relative"],
        "buoyancy_radii_m": hydro["buoyancy_radii"],
        "command_timeout_s": dynamics["command_timeout"],
    }
    proxies = []
    for index, item in enumerate(collision.findall(".//collision")):
        origin = item.find("origin")
        geometry = item.find("geometry/box")
        # The original copied these origins directly into COM-following proxies.
        proxies.append(
            box(
                f"hull_{index}",
                [float(v) for v in geometry.attrib["size"].split()],
                [float(v) for v in origin.attrib["xyz"].split()],
                quaternion([float(v) for v in origin.attrib["rpy"].split()]),
            )
        )
    body["collision_boxes"] = proxies
    frames = [
        frame("com", "cad", [-v for v in com]),
        frame("cad", "base_link", vehicle["base_link"]),
    ]
    thrusters = []
    for index, source in enumerate(vehicle["thrusters"]):
        pose = source["pose"]
        q = quaternion(pose[3:])
        w, x, y, z = q
        direction = [1 - 2 * (y * y + z * z), 2 * (x * y + w * z), 2 * (x * z - w * y)]
        thrusters.append(
            {
                "id": source["name"],
                "position_m": [pose[i] - com[i] for i in range(3)],
                "direction": direction,
                "delay_s": dynamics["delay"],
                "rise_time_s": dynamics["rise_time_constant"],
                "fall_time_s": dynamics["fall_time_constant"],
                "slew_rate_n_s": dynamics["slew_rate"],
                "forward_limit_n": dynamics["forward_max_force"],
                "reverse_limit_n": dynamics["reverse_max_force"],
                "deadband_n": dynamics["force_deadband"],
                "forward_scale": dynamics["forward_scale"],
                "reverse_scale": dynamics["reverse_scale"],
                "efficiency": hydro["thruster_efficiencies"][index],
                "propeller_radius_m": dynamics["propeller_radius"],
            }
        )
        frames.append(frame("cad", "thruster_" + source["name"], pose[:3], q))
    body["thrusters"] = thrusters
    for name in (
        "imu",
        "dvl",
        "fog",
        "depth",
        "poker",
        "torpedoes",
        "droppers",
        "claw",
        "magnet",
        "hitch",
    ):
        pose = vehicle[name]["pose"]
        frames.append(frame("cad", name + "_mount", pose[:3], quaternion(pose[3:])))
    for camera in vehicle["cameras"]:
        frames.append(
            frame(
                "cad", camera["name"] + "_mount", camera["pose"][:3], quaternion(camera["pose"][3:])
            )
        )
    robot = {
        "schema_version": 1,
        "kind": "robot",
        "vehicle": body,
        "frames": {"root": "com", "transforms": frames},
        "sensors": [],
    }
    length, width, depth = (world[key] for key in ("length", "width", "depth"))
    surface = world["water_level"]
    height = depth + world["deck_height"] + 1
    middle = surface - depth - 0.5 + height / 2
    pool = {
        "schema_version": 1,
        "kind": "world",
        "surface_pressure_pa": 101325,
        "pool": {
            "length_m": length,
            "width_m": width,
            "depth_m": depth,
            "water_level_m": surface,
            "water_density_kg_m3": world["water_density"],
            "current_m_s": world["current_velocity"],
            "current_oscillation_amplitude_m_s": world["current_oscillation_amplitude"],
            "current_oscillation_frequency_hz": world["current_oscillation_frequency"],
        },
        "collision_boxes": [
            box("floor", [length, width, 1], [length / 2, width / 2, surface - depth - 0.5]),
            box("west_wall", [1, width + 2, height], [-0.5, width / 2, middle]),
            box("east_wall", [1, width + 2, height], [length + 0.5, width / 2, middle]),
            box("south_wall", [length, 1, height], [length / 2, -0.5, middle]),
            box("north_wall", [length, 1, height], [length / 2, width + 0.5, middle]),
        ],
    }
    origin_x, origin_y, degrees = mapping["/**/zed_faker"]["ros__parameters"]["map_origin_pool"]
    yaw = -math.radians(degrees)
    position = [
        -math.cos(yaw) * origin_x + math.sin(yaw) * origin_y,
        -math.sin(yaw) * origin_x - math.cos(yaw) * origin_y,
        0,
    ]
    run = {
        "schema_version": 2,
        "robot": "../robots/talos_dynamics.yaml",
        "world": "../worlds/competition_pool.yaml",
        "seed": 7,
        "timestep_ns": 2000000,
        "ticks": 1500,
        "world_placement": {"position_m": position, "yaw_rad": yaw},
        "contacts": {"model": "box_scene", "restitution": 0.1, "friction": 0.4},
        "initial": {
            "position_m": [0, 0, -1],
            "orientation_wxyz": [1, 0, 0, 0],
            "linear_velocity_m_s": [0, 0, 0],
            "angular_velocity_rad_s": [0, 0, 0],
        },
        "commands": [
            {"tick": tick, "forces_n": [4, 4, 2, 2, -2, -2, 4, 4] if tick < 1000 else [0] * 8}
            for tick in range(0, 1001, 200)
        ],
    }
    imu = vehicle["imu"]
    ahrs = {
        "schema_version": 1,
        "kind": "sensor",
        "model": "ahrs",
        "parameters": {
            "inertial": {
                "acceleration_noise": {"white_stddev": [imu["sigma_accel"]] * 3},
                "gyro_noise": {"white_stddev": [math.radians(imu["sigma_omega"])] * 3},
                "reporting": {
                    "gravity_magnitude_m_s2": sensor_overrides["imu_gravity"],
                    "force_variance": sensor_properties["imu_linear_acceleration_variance"],
                    "angular_variance": sensor_properties["imu_angular_velocity_variance"],
                },
            },
            "attitude": {
                "angle_stddev_rad": math.radians(imu["sigma_angle"]),
                "heading_drift_rad_s": math.radians(sensor_overrides["imu_yaw_drift"]) / 60,
                "reported_variance": sensor_properties["imu_orientation_variance"],
            },
        },
    }
    inertial_robot = {
        **robot,
        "sensors": [
            {
                "id": "imu",
                "frame": "imu_mount",
                "mount_frame": "imu_mount",
                "period_ns": round(1e9 / sensor_properties["imu_rate"]),
                "profile": "../sensors/talos_ahrs.yaml",
            },
            {
                "id": "fog",
                "frame": "fog_mount",
                "mount_frame": "fog_mount",
                "period_ns": 2000000,
                "model": "fog",
                "parameters": {
                    "axes": [[0, 0, 1]],
                    "gyro_noise": {"white_stddev": [0, 0, math.radians(0.01)]},
                    "reported_variance": [0, 0, max(1e-9, math.radians(0.01) ** 2)],
                },
            },
        ],
    }
    inertial_run = {**run, "robot": "../robots/talos_inertial.yaml"}
    header = "# Generated from pinned original content; see docs/reference/TALOS_PHYSICS_PACK.md.\n"
    artifacts = {
        "content/robots/talos_dynamics.yaml": header
        + "# Physics/mount slice; sensors and visual mechanisms are not yet instantiated.\n"
        + yaml.safe_dump(robot, sort_keys=False),
        "content/worlds/competition_pool.yaml": header + yaml.safe_dump(pool, sort_keys=False),
        "content/examples/talos_pool.yaml": header
        + "# Scripted physics example, not the competition mission.\n"
        + yaml.safe_dump(run, sort_keys=False),
        "content/sensors/talos_ahrs.yaml": header
        + "# Original noise-enabled inertial/attitude settings; not hardware identification.\n"
        + yaml.safe_dump(ahrs, sort_keys=False),
        "content/robots/talos_inertial.yaml": header
        + "# Dynamics/mounts plus IMU and FOG; other devices and mechanisms remain open.\n"
        + yaml.safe_dump(inertial_robot, sort_keys=False),
        "content/examples/talos_inertial_pool.yaml": header
        + "# Scripted inertial acquisition example, not the competition mission.\n"
        + yaml.safe_dump(inertial_run, sort_keys=False),
    }
    metadata = {
        "scope": "Original Talos dynamics, static hull/pool proxies and rigid mounts, plus a separate noise-enabled IMU/FOG assembly. Scripted commands; no other devices, visuals, tasks or stack adapters.",
        "parameter_status": hydro["parameter_status"],
        "sources_sha256": sources,
        "importer_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "pyyaml_version": yaml.__version__,
        "outputs_sha256": {
            name: hashlib.sha256(text.encode()).hexdigest() for name, text in artifacts.items()
        },
    }
    artifacts["docs/reference/talos_physics_sources.json"] = json.dumps(metadata, indent=2) + "\n"
    for name, text in artifacts.items():
        destination = ROOT / name
        if args.check:
            if destination.read_text() != text:
                raise RuntimeError(f"generated content differs: {name}")
        else:
            destination.write_text(text)
    print(
        f"{'Verified' if args.check else 'Generated'} {len(artifacts)} pinned native content files"
    )


if __name__ == "__main__":
    main()
